import { NextResponse } from "next/server";

export async function GET() {
  const xsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>XML Sitemap</title>
        <meta name="robots" content="noindex, follow"/>
        <style type="text/css">
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #333; background: #f8fafc; }
          .container { max-width: 1200px; margin: 0 auto; padding: 2rem 1rem; }
          h1 { font-size: 1.5rem; font-weight: 700; color: #1e293b; margin-bottom: 0.25rem; }
          .subtitle { color: #64748b; font-size: 0.875rem; margin-bottom: 1.5rem; }
          .count { background: #e2e8f0; color: #475569; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; margin-left: 0.5rem; }
          table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 0.5rem; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
          th { background: #f1f5f9; padding: 0.75rem 1rem; text-align: left; font-size: 0.75rem; font-weight: 600; color: #475569; text-transform: uppercase; letter-spacing: 0.05em; }
          td { padding: 0.625rem 1rem; border-top: 1px solid #e2e8f0; font-size: 0.875rem; }
          tr:hover td { background: #f8fafc; }
          a { color: #2563eb; text-decoration: none; }
          a:hover { text-decoration: underline; }
          .priority { text-align: center; }
          .date { color: #64748b; white-space: nowrap; }
          .freq { color: #64748b; text-transform: capitalize; }
          footer { text-align: center; margin-top: 2rem; color: #94a3b8; font-size: 0.75rem; }
        </style>
      </head>
      <body>
        <div class="container">
          <!-- Sitemap Index -->
          <xsl:if test="sitemap:sitemapindex">
            <h1>XML Sitemap Index</h1>
            <p class="subtitle">
              This sitemap index contains
              <span class="count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></span>
              sitemaps.
            </p>
            <table>
              <thead>
                <tr>
                  <th>Sitemap URL</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <!-- URL Set -->
          <xsl:if test="sitemap:urlset">
            <h1>XML Sitemap</h1>
            <p class="subtitle">
              This sitemap contains
              <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span>
              URLs.
            </p>
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  <th style="width:120px">Priority</th>
                  <th style="width:120px">Change Freq</th>
                  <th style="width:180px">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <xsl:sort select="sitemap:priority" order="descending"/>
                  <tr>
                    <td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
                    <td class="priority"><xsl:value-of select="sitemap:priority"/></td>
                    <td class="freq"><xsl:value-of select="sitemap:changefreq"/></td>
                    <td class="date"><xsl:value-of select="substring(sitemap:lastmod, 1, 10)"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <footer>
            Generated by MyBlog Sitemap Engine
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

  return new NextResponse(xsl, {
    headers: {
      "Content-Type": "application/xslt+xml; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
